# Generated by Django 4.0.4 on 2022-05-22 20:30

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listaDeRegalos', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anfitrion',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.customuser')),
                ('phone', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('users.customuser', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('BO', 'Boda'), ('XV', 'XV Años'), ('BA', 'Bautizos'), ('IN', 'Infantiles'), ('PH', 'Para él'), ('PM', 'Para ella')], max_length=2)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('guests', models.TextField(max_length=2000)),
                ('address', models.TextField(max_length=500)),
                ('festejado_first_name', models.CharField(max_length=50)),
                ('festejado_last_name', models.CharField(max_length=50)),
                ('festejado_age', models.PositiveIntegerField(default=0)),
                ('regalos', models.CharField(max_length=300)),
                ('card', models.CharField(max_length=19)),
                ('cvv', models.CharField(max_length=3)),
                ('terminado', models.BooleanField(default=False)),
                ('total', models.IntegerField(default=0)),
                ('anfitrion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anfitrion_user_set', to=settings.AUTH_USER_MODEL)),
                ('lista_regalo', models.ManyToManyField(to='listaDeRegalos.listaderegalos')),
            ],
        ),
    ]
