# Generated by Django 4.0.4 on 2023-11-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anfitrion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='regalos',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
